
format = '''
â–² ğŸ‘Ÿ $all$character

'''

[cmd_duration]
disabled=true

[character]
format = '  '

[nodejs]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[docker_context]
disabled = true

[git_branch]
symbol = ''
style = 'red'

[git_status]
disabled = true
