# Default
# format = '''
# â–² ðŸ‘Ÿ $directory$git_branch$character
# '''

# For recordings
format = '''
â–² ðŸ‘Ÿ $directory$character
'''

[cmd_duration]
disabled = true

[character]
format = ''

[docker_context]
disabled = true

[git_branch]
symbol = ''
style = 'red'

[git_status]
disabled = true
